on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Terser
        run: npm install -g terser
      - name: Create dist directory
        run: mkdir -p ./dist
      - name: Copy file within repo
        run: cp ./src/ImageZoom.js ./dist/ImageZoom.js
      - name: Minify JavaScript
        run: terser ./src/ImageZoom.js --compress -o ./dist/ImageZoom.min.js
      - name: Auto commit minified files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Build dist folder"
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  
  deploy:    
    environment:
      name: github-pages
      url: ${\{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
